### ISSUE TITLE
Potential Mismatches between bound and unbound pdbs

### ISSUE THREAD

**Issue by MattMcPartlon** [piercelab/antibody_benchmark#1]
I'm getting very large RMSD's between unbound/bound receptor chains for a few targets.

Upon further inspection, it almost appears that the bound and unbound chains have 

I'm not sure, but e.g. 6B0S is listed as an easy target, yet the receptor bound/unbound RMSD is >10A.
![6B0S Mismatch](https://user-images.githubusercontent.com/35821457/181352547-66f25ae5-551a-416c-90ef-822b32418348.png)

This is not the only target exhibiting this issue, some others are 5CX7 and 3JM9 (plus a few more). Is this normal?

**Comment by bpierce12** [comment]
Hi Matt,

Thank you for checking about that. Those RMSDs are for the overall antibody Fab structure, and the relatively high values are due to the hinge between the variable and constant domains moving between the unbound and bound versions of the antibody. However, for docking and for docking difficulty classification we are just focused on the variable domains (which are what bind the antigen), and there is very little conformational change between the unbound and bound variable domains and CDR loops for that case. I've attached the coordinates of the unbound superposed onto bound receptor by variable domain for 6B0S. Based on precedent, we provide benchmark PDBs with coordinates of full unbound/bound receptor or ligand proteins superposed onto each other, which in the case of antibody Fab structures can be slightly misleading in terms of showing binding conformational changes of the CDR loops and interface residues (the latter is what we use for the docking difficulty classifications).

Hope this helps, please let me know if you have any more questions.

Best,
Brian

[6B0S_r_u_aligned_to_bound.pdb.txt](https://github.com/piercelab/antibody_benchmark/files/9219431/6B0S_r_u_aligned_to_bound.pdb.txt)
[6B0S_r_b.pdb.txt](https://github.com/piercelab/antibody_benchmark/files/9219432/6B0S_r_b.pdb.txt)
